version: 0.2

env:
    variables:
        S3_BUCKET: "qa-gigsumo-login"
        BUILD_ENV: "qa"
phases:
 install:
    runtime-versions:
        nodejs: 16
    commands:
    - echo $CODEBUILD_SRC_DIR
    - npm install -g @angular/cli@15.2.11
    - npm cache clean --force
    - rm package-lock.json
 pre_build:
    commands:
    - npm install
 build:
    on-failure: ABORT
    commands:
    - echo build started on `date`
    - ./node_modules/@angular/cli/bin/ng build -c=qa
    - ls -l -F
 post_build:
    commands:
            # Clear S3 bucket.
            - aws s3 rm s3://${S3_BUCKET} --recursive
            - echo S3 bucket is cleared.
            - aws s3 cp dist/Gigsumo s3://${S3_BUCKET} --recursive
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    discard-paths: yes
    base-directory: 'dist*'
cache:
  paths:
    - node_modules/
